sudo: true
language: php
php:
  - 7.0
  - 5.6
  - 5.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq mecab mecab-ipadic-utf8 libmecab-dev
  - chmod 755 .travis_mecab.sh
  - ./.travis_mecab.sh
before_script:
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
script:
  - mkdir -p build/logs
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100

after_script:
  - php vendor/bin/coveralls -v