sudo: true
language: php
php:
  - 7.0
  - 5.6
  - 5.5
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -y mecab mecab-ipadic-utf8
  - sudo apt-get install php5-dev libmecab-dev build-essential
before_script:
  - chmod +x .travis_mecab.sh
  - wget http://getcomposer.org/composer.phar
  - php composer.phar install --dev --no-interaction
script:
  - ./.travis_mecab.sh
  - php vendor/bin/phpunit -c phpunit.xml.dist
  - php coverage-checker.php build/logs/clover.xml 100

after_script:
  - php vendor/bin/coveralls -v